<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [11]:
class Matrix_multiplication:
    
    def __init__(self, A,B):
        self.A = A
        self.B = B
        self.row_matrix_A = len(A)
        self.Column_matrix_A = len(A[0])
        self.row_matrix_B = len(B)
        self.Column_matrix_B = len(B[0])
        
        self.Matrix_zero()
        
    def Matrix_zero(self):
        Matrix = [] 
        for i in range(0,self.row_matrix_A):
            Matrix.append([])
            for j in range (0,self.Column_matrix_B):
                Matrix[-1].append(0)
        return Matrix        
        
    def Matrix_mult(self):
        Result_matrix = self.Matrix_zero()
        if self.Column_matrix_A != self.row_matrix_B:
            return print ("Matrix product is not possible")
        else:
            print ("Matrix product is possible")

            for i in range (self.row_matrix_A):
                
                for j in range(self.Column_matrix_B):
                    
                    for k in range (self.Column_matrix_A):
                        Result_matrix[i][j]+= self.A[i][k] * self.B[k][j]
        return print(Result_matrix)            
                  
        

        


In [12]:
A = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]
# 3x4 matrix
B = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]

C = Matrix_multiplication(A,B)

C.Matrix_mult()



Matrix product is possible
[[114, 160, 60, 27], [74, 97, 73, 14], [119, 157, 112, 23]]


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

<div class="alert alert-block alert-success"><b>Reference:</b> 
1. https://www.quora.com/How-can-we-pick-an-element-from-an-array-with-probability-proportional-to-the-element
2. https://www.quora.com/How-can-we-pick-an-element-from-an-array-with-probability-proportional-to-the-element/answer/Pradeep-George-Mathias




    
</div>

In [386]:
from random import uniform
class Propor_Prob:
    
    def __init__(self, A):
        self.A = A
        self.sum_list()
        self.uniform_random()
        self.cum_sum_prob()
        self.pick_a_number_from_list()

    
    def sum_list(self):
        total = 0
        for i in self.A:
            total += i
        return total
    
    def uniform_random(self):
        randomx = uniform(0.0,1)
        return randomx
    
    def cum_sum_prob(self):
        prob_list = [] 


        running_total = 0
        Cum_prob_list=[]
        
        for j in range(len(self.A)):
            running_total += self.A[j]
            Cum_prob_list.append(running_total/self.sum_list())
        
        return Cum_prob_list
    

         
            
    def pick_a_number_from_list(self):
        cum_list = self.cum_sum_prob()
        random_list = self.uniform_random()
        for i in range (len(self.cum_sum_prob())):
            if (random_list <= cum_list[i] ):
                break
        return self.A[i]
 


In [387]:


def sampling_based_on_magnitued():
    A = [0,5 ,27 ,6, 13, 39, 100, 45, 10, 79]
    numberx = Propor_Prob(A)
    for i in range(1,100):
        number = numberx.pick_a_number_from_list()
        print(number)

sampling_based_on_magnitued()

39
39
27
79
79
100
100
79
100
39
100
45
39
79
13
79
13
10
100
100
100
100
27
79
39
10
79
79
13
79
39
100
45
100
27
79
10
100
79
100
79
79
79
79
100
79
79
79
100
79
100
10
79
100
45
100
39
5
100
100
27
45
45
100
79
100
100
100
100
10
100
79
45
79
39
100
79
100
45
100
39
79
79
39
100
100
5
27
100
39
79
10
39
45
100
100
100
10
100


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

<div class="alert alert-block alert-success"><b>Reference:</b>  https://stackoverflow.com/questions/19084443/replacing-digits-with-str-replace
<br>          - https://stackoverflow.com/questions/1249388/removing-all-non-numeric-characters-from-string-in-python</div>

In [406]:
import re
class replace_digits:
    def __init__(self, Old_Str):
        self.Old_Str = Old_Str
        self.replace_str()
    
    def replace_str(self):
        new_Str=re.sub("[^\d\.]", "", self.Old_Str)
        new_Str2 = re.sub('\d', '#', new_Str)

        return (new_Str2)       
                
        


y=replace_digits("a2b3c4")
z=y.replace_str()
print(z)

###


<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [360]:
import math

class display_dash_board:
    def __init__(self, Student,Marks):
        self.Student = Student
        self.Marks= Marks
        
    def desc_order(self):
        for i in range(0,len(self.Marks)-1):
            for k in range (i+1,len(self.Marks) ):
                if self.Marks[i] < self.Marks[k]:
                    self.Marks[i] , self.Marks[k] = self.Marks[k] , self.Marks[i]
                    self.Student[i] , self.Student[k] = self.Student[k] , self.Student[i]
        res = [m+'  '+ str(n) for m,n in zip(self.Student,self.Marks)]
        
        return (res)
    
    def Top5(self):
        top5_list = []
        result_list = self.desc_order()
        for i in range(0,5):
            top5_list.append(result_list[i])
        return(top5_list)
    
    def bottom5(self):
        bottom5_list = []
        result_list = self.desc_order()
        for i in range(len(result_list)-1,len(result_list)-6,-1) :
            bottom5_list.append(result_list[i])
        return(bottom5_list)
    
    def students_within_25_and_75(self):
        students_within_25_and_75_list = []
        result_list = self.desc_order()
        for i in range(math.floor(len(result_list)*0.75),math.ceil(len(result_list)*0.25)-1,-1) :
            students_within_25_and_75_list.append(result_list[i])
        return(students_within_25_and_75_list)
    
    def final_Result(self):
        return self.Top5(), self.bottom5(), self.students_within_25_and_75()
            
                
        

In [361]:
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

In [362]:
y = display_dash_board (Students, Marks)

In [363]:
x = y.students_within_25_and_75()
print(x)

['student9  35', 'student6  43', 'student1  45', 'student7  47', 'student5  48']


In [366]:
top_5_students, least_5_students, students_within_25_and_75 = y.final_Result()
print(top_5_students)
print(least_5_students)
print(students_within_25_and_75)

['student8  98', 'student10  80', 'student2  78', 'student5  48', 'student7  47']
['student3  12', 'student4  14', 'student9  35', 'student6  43', 'student1  45']
['student9  35', 'student6  43', 'student1  45', 'student7  47', 'student5  48']


<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [404]:
import math

class closest_points_to_p:
    def __init__(self, S,P):
        self.S = S
        self.P = P
        
    def distance_points(self):
        distance_list=[]
        append_list = []
        for i in range (0,len(self.S)):
            numerator = self.S[i][0] * self.P[0] + self.S[i][1] * self.P[1]
            denominator = math.sqrt(self.S[i][0] ** 2 + self.S[i][1] ** 2) * math.sqrt(self.P[0] ** 2 + self.P[1] ** 2)
            Div = numerator/denominator
            distance = math.acos (Div)
            distance_list.append(round(distance,2))
            #list_a, list_b = zip(*self.S)
            
        return distance_list
    
    def desc_order(self):
        distance_list_sort = self.distance_points()
        list_a, list_b = zip(*self.S)
        list_a = list(list_a)
        list_b = list(list_b)
        for i in range(0,len(distance_list_sort)-1):
            for k in range (i+1,len(distance_list_sort) ):
                if distance_list_sort[i] > distance_list_sort[k]:
                    distance_list_sort[i] , distance_list_sort[k] = distance_list_sort[k] , distance_list_sort[i]
                    list_a[i] , list_a[k] = list_a[k] , list_a[i]
                    list_b[i] , list_b[k] = list_b[k] , list_b[i]
        res = list(map(tuple, zip(list_a, list_b)))

        return (res)

        




S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
#print(P[1])
xx = closest_points_to_p(S,P)
DL = xx.desc_order()
print(DL)
#points = closest_points_to_p(S, P)
print() #print the returned values

[(6, -7), (1, -1), (6, 0), (-5, -8), (-1, -1), (3, 4), (1, 2), (0, 6), (-1, 1)]



<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

<div class="alert alert-block alert-success"><b>Reference:</b> 
https://www.programcreek.com/python/example/134/re.split   
</div>

In [5]:

import re
class segregate_line:
    def __init__ (self, Red,Blue,Lines):
        self.Red = Red
        self.Blue = Blue
        self.Lines = Lines
    def Lines_Coeff(self,pos):
        a, b, c = [float(x.strip()) for x in re.split('x|y', self.Lines[pos])]
        return a,b,c
    
    def Red_line_Sep(self):   
        Red_line_List_final = []
        for i in range(0,len(self.Lines)):
            pos_a,pos_b,pos_c=  self.Lines_Coeff(i)
            Red_line_List=[]
            for j in range (0, len(self.Red)):
                red = pos_a * self.Red[j][0] + pos_b * self.Red[j][1] + pos_c
                Red_line_List.append(red)
            Red_line_List_final.append(Red_line_List)
                
        return Red_line_List_final
    
    def Blue_line_Sep(self):   
        Blue_line_List_final = []
        for i in range(0,len(self.Lines)):
            pos_a,pos_b,pos_c=  self.Lines_Coeff(i)
            Blue_line_List =[]
            for j in range (0, len(self.Blue)):
                Blue = pos_a * self.Blue[j][0] + pos_b * self.Blue[j][1] + pos_c
                Blue_line_List.append(Blue)
            Blue_line_List_final.append(Blue_line_List)

        return Blue_line_List_final
    
    def Print_Yes_No(self):
        Blue = [all(f < 0 for f in i) for i in self.Blue_line_Sep()]
        Red = [all(l>0 for l in i) for i in self.Red_line_Sep()]

        for i in range(len(Blue)):
            if(Blue[i]==True and Red[i]==True):
                print("Yes")
            else:
                print('No')

In [6]:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

y = segregate_line(Red,Blue,Lines)
z = y.Print_Yes_No()
print(z)

Yes
No
No
Yes
None


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [93]:


def curve_smoothing(String):
    S = String.split(',')
    #print(S[2])
    #print(S[6])
    #String = S.split(',')
    #print(String)
    Len_String = len(S)
    #print(Len_String)
    No_of_digits = 0
    position_list = []
#find the position of the digits
    position_list.append(0)
    for i in range(0, Len_String):

        if S[i].isdigit():
            position_list.append(i)

    position_list.append(Len_String-1)

    position_list = list(dict.fromkeys(position_list))

    x= 0 #starting position
    list2=[]
    #len_2= len()
    sum_X =0
    list_ = 'List_'

    list_name =[]
    for k in range(0,len(position_list)-1):
        list_name.append(list_ + str(k))

    #print(list_name)
#Create separate list
    for k in range(0,len(position_list)):
        if k+1 >= len(position_list):
            break;
        list_name[k] = S[position_list[k]:position_list[k+1]+1]
        #print(list_name[k])


# Run two loops
    for j in range(0,len(list_name)):
        
        if j>0:
            #Update the first digit with the any digit of the previous list
            #print(str(list_name[j-1][0]))
            list_name[j][0] = str(list_name[j-1][0])

        No_of_digits = 0
        Empty_list =[]
        sum_s = 0
        for i in range(0,len(list_name[j])):
            #print(j,list_name[j][i])
            if list_name[j][i].isdigit():

                No_of_digits+= 1
                Empty_list.append(float(list_name[j][i]))
                #print(i)
                if i == 0 or i == len(list_name[j])-1:
                    sum_s += Empty_list[No_of_digits-1]
        Equal_distribution = int(sum_s/len(list_name[j]))

        for l in range(0,len(list_name[j])):
            list_name[j][l] = Equal_distribution

    final_list = []  
    for i in range(0,len(list_name)):
        for j in range(0,len(list_name[i])):
            final_list.append(list_name[i][j])
        

    return final_list
String= "_,_,30,_,_,_,50,_,_"
#String="36,_,_,24"
y= curve_smoothing(String)

#print(list_name[0],list_name[1],list_name[2])
print(y)
        
        







[10, 10, 10, 12, 12, 12, 12, 12, 4, 4, 4]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [363]:
class compute_conditional_probabilites:
    def __init__(self,A):
        self.A = A
    def counting_S(self):
        Empty_list = []
        for i in range (0,len(self.A)):
            Empty_list.append(self.A[i][1])
            
        unique_list = list(dict.fromkeys(Empty_list))    
        dict_S_count = dict()
        for item_list in unique_list:
            dict_key = item_list
            counter  = 0
            for j in Empty_list:
                if item_list ==j:
                    counter += 1
                    
                
            dict_S_count[dict_key] = counter
        return unique_list,dict_S_count
    
    def counting_F(self):
        Empty_list = []
        for i in range (0,len(self.A)):
            Empty_list.append(self.A[i][0])
            
        unique_list = list(dict.fromkeys(Empty_list))    
        dict_F_count = dict()
        for item_list in unique_list:
            dict_key = item_list
            counter  = 0
            for j in Empty_list:
                if item_list ==j:
                    counter += 1
                    
                
            dict_F_count[dict_key] = counter
        return unique_list
    
    def zip_S_F(self):
        uniq_s, dic_S_count = self.counting_S()
        uniq_f = self.counting_F()
        Concated_list = []
        for i in uniq_f:
            
            for j in uniq_s:
               
                for k in range (0,len(self.A)):
                    if i == self.A[k][0] and j == self.A[k][1]:
                        Concated_list.append(i+j)
                        
        # Concated All list
        
        Concated_All_list = []
        for i in uniq_f:
            
            for j in uniq_s:
                Concated_All_list.append (i+j)
                
        # S list with the same length
        S_list =[]
        for item in Concated_All_list:
            S_list.append(item[2:4])
            
        S_list_values = []
        for item_list in S_list:
            dict_value = dic_S_count[item_list]
            S_list_values.append(dict_value)
            
    
        # concated intersection all dictionary
        dict_intersection_count = dict()
        for item_list in Concated_All_list:
            dict_key = item_list
            counter = 0
            for item in Concated_list:
                if item_list == item:
                    counter +=1
            dict_intersection_count[dict_key] = counter
        return S_list, S_list_values,dict_intersection_count
    
    
    def creating_list_within_list(self):
        S_list, S_list_values,dict_intersection_count = self.zip_S_F()
        intersection_list = list (dict_intersection_count.keys())
        intersection_list_Values = list (dict_intersection_count.values())
        uniq_s, dic_S_count = self.counting_S()
        uniq_f = self.counting_F()
        intersection_list_1=[]
        intersection_list_Values_1 =[]
        S_list_1 =[]
        S_list_values_1 =[]
        for i in range(0,len(intersection_list),3):
            intersection_list_2=[]
            intersection_list_Values_2 =[]
            
            S_list_2=[]
            S_list_values_2 =[]
            for j in range (0,len(uniq_s)):
                intersection_list_2.append(intersection_list[i+j])
                intersection_list_Values_2.append(intersection_list_Values[i+j])
                S_list_2.append(S_list[i+j])
                S_list_values_2.append(S_list_values[i+j])
            intersection_list_1.append(intersection_list_2)
            intersection_list_Values_1.append(intersection_list_Values_2)
            S_list_1.append(S_list_2)
            S_list_values_1.append(S_list_values_2)
            
                
        #   
        return S_list_1,S_list_values_1,intersection_list_1, intersection_list_Values_1 
    
    
    def print_format(self):
        S_list_1,S_list_values_1,intersection_list_1, intersection_list_Values_1= self.creating_list_within_list()
        format_print_F ='P(F='
        format_print_S ='|S=='
        format_print_last = ')='
        format_print_1 =[]
        for i in range(0,len(S_list_1)):
            format_print_2 =[]
            for j in range(0,len(S_list_1[0])):
                format_print_2.append(format_print_F+ intersection_list_1[i][j][0:2]+format_print_S +S_list_1[i][j]+format_print_last+ str(intersection_list_Values_1[i][j])+'/'+str(S_list_values_1[i][j]))
                                      
                
            format_print_1.append(format_print_2)
        list_2= ['a.','b.','c.','d.','e.']
        final_list = [[]]
        
        # Zero Matrix
        Matrix = [] 
        for i in range(0,5):
            Matrix.append([])
            for j in range (0,4):
                Matrix[-1].append(0)

            
            
            
        
        
        return list_2,format_print_1
        
  

In [364]:
A = [['F1', 'S1'], ['F2', 'S2'], ['F3', 'S3'], ['F1', 'S2'], ['F2', 'S3'], ['F3', 'S2'], ['F2', 'S1'], ['F4', 'S1'],
     ['F4', 'S3'], ['F5', 'S1']]

In [366]:
y = compute_conditional_probabilites(A)

In [368]:
dummy_list1,dummy_list2  = y.print_format()

In [369]:
dummy_list1

['a.', 'b.', 'c.', 'd.', 'e.']

In [370]:
dummy_list2

[['P(F=F1|S==S1)=1/4', 'P(F=F1|S==S2)=1/3', 'P(F=F1|S==S3)=0/3'],
 ['P(F=F2|S==S1)=1/4', 'P(F=F2|S==S2)=1/3', 'P(F=F2|S==S3)=1/3'],
 ['P(F=F3|S==S1)=0/4', 'P(F=F3|S==S2)=1/3', 'P(F=F3|S==S3)=1/3'],
 ['P(F=F4|S==S1)=1/4', 'P(F=F4|S==S2)=0/3', 'P(F=F4|S==S3)=1/3'],
 ['P(F=F5|S==S1)=1/4', 'P(F=F5|S==S2)=0/3', 'P(F=F5|S==S3)=0/3']]

In [385]:
for i,j in zip(range(len(dummy_list1)), range(len(dummy_list2))):
      print(dummy_list1[i],dummy_list2[j] )
    
    
        
        
  

a. ['P(F=F1|S==S1)=1/4', 'P(F=F1|S==S2)=1/3', 'P(F=F1|S==S3)=0/3']
b. ['P(F=F2|S==S1)=1/4', 'P(F=F2|S==S2)=1/3', 'P(F=F2|S==S3)=1/3']
c. ['P(F=F3|S==S1)=0/4', 'P(F=F3|S==S2)=1/3', 'P(F=F3|S==S3)=1/3']
d. ['P(F=F4|S==S1)=1/4', 'P(F=F4|S==S2)=0/3', 'P(F=F4|S==S3)=1/3']
e. ['P(F=F5|S==S1)=1/4', 'P(F=F5|S==S2)=0/3', 'P(F=F5|S==S3)=0/3']


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [115]:
class string_features:
    def __init__(self,S1, S2):
        self.S1= S1
        self.S2 = S2
        self.split_string()
    def split_string(self):
        string_S1 = self.S1.split(' ')
        string_S2 = self.S2.split(' ')
        return string_S1, string_S2
    
    def common_words(self):
        list1, list2 = self.split_string()
        counter = 0
        for i in list1:
            for j in list2:
                if i ==j:
                    counter+=1
        return counter
    
    def S1_Not_S2(self):
        list1, list2 = self.split_string()
        counter = 0
        Empty_List = []
        for i in list1:
            for j in list2:
                if i == j:
                    Empty_List.append(i)
                    
        for l in range (0, len(Empty_List)):
            list1.remove(Empty_List[l])
        return list1
            
    def S2_Not_S1(self):
        list1, list2 = self.split_string()
        counter = 0
        Empty_List = []
        for i in list1:
            for j in list2:
                if i == j:
                    Empty_List.append(i)
                    
        for l in range (0, len(Empty_List)):
            list2.remove(Empty_List[l])
            
        
        
        return list2
                    
    
    
    
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
y= string_features(S1,S2)


z=y.common_words()
print('Common words-{}'.format(z))
z=y.S1_Not_S2()
print('S1 not S2{}'.format(z))
z = y.S2_Not_S1()
print('S2 not S1{}'.format(z))
        
    
        
        

Common words-7
S1 not S2['first', 'F', '5']
S2 not S1['second', 'S', '3']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [391]:
A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]

In [392]:
A[1][1]

0.5

In [394]:
import math
class compute_log_loss:
    def __init__(self,A):
        self.A =A
        self.len_A = len(A)
    def compute_loss(self):
        sum_log_loss =0
        for i in range(0,self.len_A ):
            sum_log_loss += (self.A[i][0] * math.log10(self.A[i][1])) + ((1-self.A[i][0]) * math.log10(1-self.A[i][1]))
        return   -1 * sum_log_loss/self.len_A
    

z= compute_log_loss(A)
y =z.compute_loss()
print(y)
        
    

0.42430993457031635
